
x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: 0.1.1
  publishedVersion: 0.1.1
  images:
    nexus_backend: {}
    connector_service: {}
    data_stream_service: {}
    ubbagent: {}

required:
  - name
  - namespace
  - reportingSecret

properties:
  name:
    type: string
    description: Name of the deployment
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    description: Namespace to deploy into
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    title: Reporting Secret
    description: The secret containing the reporting credentials.
    x-google-marketplace:
      type: REPORTING_SECRET
  domain:
    type: string
    title: Ingress Domain
    description: The domain name to use for the ingress (e.g., api.example.com).
  enableIngress:
    type: boolean
    title: Enable Ingress
    description: Whether to enable Ingress and Managed Certificates.
    default: true
